---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - kibana_wrapper::default
    attributes:
      nginx:
        default_site_enabled: false
        install_method:       source
        source:
          checksum: df73c1b468cebaf3530a5de910bed45ff2cfccf2cf4b9215d0aa0f4e39cf4460
          modules:
            - nginx::http_ssl_module
            - nginx::http_realip_module
            - nginx::http_gzip_static_module
          url:      http://nginx.org/download/nginx-1.7.10.tar.gz
          version:  1.7.10
      java:
        jdk:
          '8':
            x86_64:
              checksum: e145c03a7edc845215092786bcfba77e
              url:      http://download.oracle.com/otn-pub/java/jdk/8u31-b13/jdk-8u31-linux-x64.tar.gz
        jdk_version: "8"
        oracle:
          accept_oracle_download_terms: true
